packages: []

catalogs:
  build:
    '@unocss/eslint-plugin': ^0.60.4
    '@unocss/preset-icons': ^0.60.4
    '@unocss/reset': ^0.60.4
    '@unocss/transformer-directives': ^0.60.4
    '@vitejs/plugin-vue': ^5.2.4
    fast-glob: ^3.3.3
    fs-extra: ^11.3.0
    gray-matter: ^4.0.3
    markdown-it: ^14.1.0
    markdown-it-anchor: ^9.2.0
    markdown-it-diagram: ^1.1.4
    markdown-it-link-attributes: ^4.0.1
    markdown-it-table-of-contents: ^0.6.0
    rollup-plugin-visualizer: ^5.14.0
    unocss: ^0.60.4
    unplugin-auto-import: ^0.17.8
    unplugin-icons: ^0.19.3
    unplugin-vue-components: ^0.27.5
    unplugin-vue-markdown: ^0.26.3
    unplugin-vue-router: ^0.8.8
    vite: ^5.4.19
    vite-ssg: ^0.23.8
  dev:
    '@antfu/eslint-config': ^5.4.1
    '@iconify/json': ^2.2.343
    '@microlink/mql': ^0.14.0
    '@unhead/vue': ^1.11.20
    cross-env: ^10.1.0
    eslint: ^9.27.0
    eslint-plugin-format: ^0.1.3
    esno: ^4.8.0
    inquirer: ^12.9.6
    vue-tsc: ^2.2.10

  frontend:
    '@docsearch/css': ^3.9.0
    '@docsearch/js': ^3.9.0
    '@shikijs/markdown-it': ^1.29.2
    '@shikijs/twoslash': ^1.29.2
    '@vueuse/core': ^10.11.1
    dayjs: ^1.11.13
    diacritics: ^1.3.0
    feed: ^4.2.2
    floating-vue: ^5.2.2
    lodash-es: ^4.17.21
    mermaid: ^10.9.3
    nprogress: ^0.2.0
    swiper: ^11.2.8
    vue: ^3.5.16
    vue-final-modal: ^4.5.5
    vue-i18n: ^9.14.4
    vue-router: ^4.5.1
    vue-router-better-scroller: ^0.0.0
    vue-virtual-scroller: 2.0.0-beta.8
  types:
    '@types/fs-extra': ^11.0.4
    '@types/lodash': ^4.17.17
    '@types/lodash-es': ^4.17.12
    '@types/markdown-it': ^14.1.2
    '@types/markdown-it-link-attributes': ^3.0.5
    '@types/node': ^20.17.56
    '@types/nprogress': ^0.2.3
    typescript: ^5.8.3

onlyBuiltDependencies:
  - esbuild
  - unrs-resolver
  - vue-demi
