/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Footer: typeof import('./../src/components/Footer.vue')['default']
    Logo: typeof import('./../src/components/Logo.vue')['default']
    NavBar: typeof import('./../src/components/NavBar.vue')['default']
    Plum: typeof import('./../src/components/Plum.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToggleTheme: typeof import('./../src/components/ToggleTheme.vue')['default']
    WrapPost: typeof import('./../src/components/WrapPost.vue')['default']
  }
}
