/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdUnit: typeof import('./../src/components/Ads/AdUnit.vue')['default']
    AIPostChat: typeof import('./../src/components/Post/AIPostChat/index.vue')['default']
    AlgoliaSearchBox: typeof import('./../src/components/Headers/Search/AlgoliaSearchBox.vue')['default']
    BottomIcon: typeof import('./../src/components/Demos/components/BottomIcon.vue')['default']
    Company: typeof import('./../src/components/Projects/Company.vue')['default']
    DemoCard: typeof import('./../src/components/Demos/DemoCard.vue')['default']
    DemoDialog: typeof import('./../src/components/Demos/DemoDialog.vue')['default']
    Demos: typeof import('./../src/components/Demos/index.vue')['default']
    DemoToolbar: typeof import('./../src/components/Demos/DemoToolbar.vue')['default']
    Footer: typeof import('./../src/components/Footer.vue')['default']
    GeoMap: typeof import('./../src/components/Post/GeoMap/index.vue')['default']
    ListPosts: typeof import('./../src/components/Post/ListPosts.vue')['default']
    Logo: typeof import('./../src/components/Logo.vue')['default']
    ModalCard: typeof import('./../src/components/Demos/components/ModalCard.vue')['default']
    NavBar: typeof import('./../src/components/Headers/NavBar.vue')['default']
    NavItem: typeof import('./../src/components/Navs/NavItem.vue')['default']
    NavsList: typeof import('./../src/components/Navs/NavsList.vue')['default']
    NavsTabs: typeof import('./../src/components/Navs/NavsTabs.vue')['default']
    Plum: typeof import('./../src/components/Plum.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TechStack: typeof import('./../src/components/Projects/TechStack.vue')['default']
    Title: typeof import('./../src/components/Post/Title.vue')['default']
    ToggleTheme: typeof import('./../src/components/Headers/ToggleTheme.vue')['default']
    TwikooComment: typeof import('./../src/components/Comment/TwikooComment.vue')['default']
    VMenuWrap: typeof import('./../src/components/Headers/VMenuWrap.vue')['default']
    WordYear: typeof import('./../src/components/Post/WordYear.vue')['default']
    WrapPost: typeof import('./../src/components/WrapPost.vue')['default']
  }
}
