/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...404]': RouteRecordInfo<
      '/[...404]',
      '/:404(.*)',
      { 404: ParamValue<true> },
      { 404: ParamValue<false> },
      | never
    >,
    '/demos/': RouteRecordInfo<
      '/demos/',
      '/demos',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/interview/': RouteRecordInfo<
      '/interview/',
      '/interview',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/navs/': RouteRecordInfo<
      '/navs/',
      '/navs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/navs/libraries': RouteRecordInfo<
      '/navs/libraries',
      '/navs/libraries',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/navs/tools': RouteRecordInfo<
      '/navs/tools',
      '/navs/tools',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/': RouteRecordInfo<
      '/posts/',
      '/posts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/2021': RouteRecordInfo<
      '/posts/2021',
      '/posts/2021',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/algolia': RouteRecordInfo<
      '/posts/algolia',
      '/posts/algolia',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/aug': RouteRecordInfo<
      '/posts/aug',
      '/posts/aug',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/big-screen': RouteRecordInfo<
      '/posts/big-screen',
      '/posts/big-screen',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/bs2022': RouteRecordInfo<
      '/posts/bs2022',
      '/posts/bs2022',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/buy-car': RouteRecordInfo<
      '/posts/buy-car',
      '/posts/buy-car',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/convolution': RouteRecordInfo<
      '/posts/convolution',
      '/posts/convolution',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/debug_test': RouteRecordInfo<
      '/posts/debug_test',
      '/posts/debug_test',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/deepin': RouteRecordInfo<
      '/posts/deepin',
      '/posts/deepin',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/docker': RouteRecordInfo<
      '/posts/docker',
      '/posts/docker',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/es6': RouteRecordInfo<
      '/posts/es6',
      '/posts/es6',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/file-download': RouteRecordInfo<
      '/posts/file-download',
      '/posts/file-download',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/forwardemail': RouteRecordInfo<
      '/posts/forwardemail',
      '/posts/forwardemail',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/git': RouteRecordInfo<
      '/posts/git',
      '/posts/git',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/git-commit': RouteRecordInfo<
      '/posts/git-commit',
      '/posts/git-commit',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/gpt': RouteRecordInfo<
      '/posts/gpt',
      '/posts/gpt',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/java': RouteRecordInfo<
      '/posts/java',
      '/posts/java',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/js-re': RouteRecordInfo<
      '/posts/js-re',
      '/posts/js-re',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/make-name': RouteRecordInfo<
      '/posts/make-name',
      '/posts/make-name',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/mcp': RouteRecordInfo<
      '/posts/mcp',
      '/posts/mcp',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/md-it-diagarm': RouteRecordInfo<
      '/posts/md-it-diagarm',
      '/posts/md-it-diagarm',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/mermaid': RouteRecordInfo<
      '/posts/mermaid',
      '/posts/mermaid',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/npm-cdn': RouteRecordInfo<
      '/posts/npm-cdn',
      '/posts/npm-cdn',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/ollama': RouteRecordInfo<
      '/posts/ollama',
      '/posts/ollama',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/own-api': RouteRecordInfo<
      '/posts/own-api',
      '/posts/own-api',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/pinia': RouteRecordInfo<
      '/posts/pinia',
      '/posts/pinia',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/pnpm-pkg': RouteRecordInfo<
      '/posts/pnpm-pkg',
      '/posts/pnpm-pkg',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/pytorch': RouteRecordInfo<
      '/posts/pytorch',
      '/posts/pytorch',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/re-soup': RouteRecordInfo<
      '/posts/re-soup',
      '/posts/re-soup',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/rewrite-blazeb2': RouteRecordInfo<
      '/posts/rewrite-blazeb2',
      '/posts/rewrite-blazeb2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/sass': RouteRecordInfo<
      '/posts/sass',
      '/posts/sass',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/swiper': RouteRecordInfo<
      '/posts/swiper',
      '/posts/swiper',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/tkinter': RouteRecordInfo<
      '/posts/tkinter',
      '/posts/tkinter',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/tmpl-cli': RouteRecordInfo<
      '/posts/tmpl-cli',
      '/posts/tmpl-cli',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/train': RouteRecordInfo<
      '/posts/train',
      '/posts/train',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/vscode': RouteRecordInfo<
      '/posts/vscode',
      '/posts/vscode',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/yunshu-uninstall': RouteRecordInfo<
      '/posts/yunshu-uninstall',
      '/posts/yunshu-uninstall',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/zsh-windows': RouteRecordInfo<
      '/posts/zsh-windows',
      '/posts/zsh-windows',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/projects/': RouteRecordInfo<
      '/projects/',
      '/projects',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/zh/': RouteRecordInfo<
      '/zh/',
      '/zh',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/zh/demos/': RouteRecordInfo<
      '/zh/demos/',
      '/zh/demos',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/zh/interview/': RouteRecordInfo<
      '/zh/interview/',
      '/zh/interview',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/zh/navs/': RouteRecordInfo<
      '/zh/navs/',
      '/zh/navs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/zh/navs/libraries': RouteRecordInfo<
      '/zh/navs/libraries',
      '/zh/navs/libraries',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/zh/navs/tools': RouteRecordInfo<
      '/zh/navs/tools',
      '/zh/navs/tools',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/zh/posts/': RouteRecordInfo<
      '/zh/posts/',
      '/zh/posts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/zh/posts/2021': RouteRecordInfo<
      '/zh/posts/2021',
      '/zh/posts/2021',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/zh/posts/algolia': RouteRecordInfo<
      '/zh/posts/algolia',
      '/zh/posts/algolia',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/zh/posts/aug': RouteRecordInfo<
      '/zh/posts/aug',
      '/zh/posts/aug',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/zh/posts/big-screen': RouteRecordInfo<
      '/zh/posts/big-screen',
      '/zh/posts/big-screen',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/zh/posts/bs2022': RouteRecordInfo<
      '/zh/posts/bs2022',
      '/zh/posts/bs2022',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/zh/posts/buy-car': RouteRecordInfo<
      '/zh/posts/buy-car',
      '/zh/posts/buy-car',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/zh/posts/convolution': RouteRecordInfo<
      '/zh/posts/convolution',
      '/zh/posts/convolution',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/zh/posts/debug_test': RouteRecordInfo<
      '/zh/posts/debug_test',
      '/zh/posts/debug_test',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/zh/posts/deepin': RouteRecordInfo<
      '/zh/posts/deepin',
      '/zh/posts/deepin',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/zh/posts/docker': RouteRecordInfo<
      '/zh/posts/docker',
      '/zh/posts/docker',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/zh/posts/es6': RouteRecordInfo<
      '/zh/posts/es6',
      '/zh/posts/es6',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/zh/posts/file-download': RouteRecordInfo<
      '/zh/posts/file-download',
      '/zh/posts/file-download',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/zh/posts/forwardemail': RouteRecordInfo<
      '/zh/posts/forwardemail',
      '/zh/posts/forwardemail',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/zh/posts/git': RouteRecordInfo<
      '/zh/posts/git',
      '/zh/posts/git',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/zh/posts/git-commit': RouteRecordInfo<
      '/zh/posts/git-commit',
      '/zh/posts/git-commit',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/zh/posts/gpt': RouteRecordInfo<
      '/zh/posts/gpt',
      '/zh/posts/gpt',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/zh/posts/java': RouteRecordInfo<
      '/zh/posts/java',
      '/zh/posts/java',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/zh/posts/js-re': RouteRecordInfo<
      '/zh/posts/js-re',
      '/zh/posts/js-re',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/zh/posts/make-name': RouteRecordInfo<
      '/zh/posts/make-name',
      '/zh/posts/make-name',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/zh/posts/mcp': RouteRecordInfo<
      '/zh/posts/mcp',
      '/zh/posts/mcp',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/zh/posts/md-it-diagarm': RouteRecordInfo<
      '/zh/posts/md-it-diagarm',
      '/zh/posts/md-it-diagarm',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/zh/posts/mermaid': RouteRecordInfo<
      '/zh/posts/mermaid',
      '/zh/posts/mermaid',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/zh/posts/npm-cdn': RouteRecordInfo<
      '/zh/posts/npm-cdn',
      '/zh/posts/npm-cdn',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/zh/posts/ollama': RouteRecordInfo<
      '/zh/posts/ollama',
      '/zh/posts/ollama',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/zh/posts/own-api': RouteRecordInfo<
      '/zh/posts/own-api',
      '/zh/posts/own-api',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/zh/posts/pinia': RouteRecordInfo<
      '/zh/posts/pinia',
      '/zh/posts/pinia',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/zh/posts/pnpm-pkg': RouteRecordInfo<
      '/zh/posts/pnpm-pkg',
      '/zh/posts/pnpm-pkg',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/zh/posts/pytorch': RouteRecordInfo<
      '/zh/posts/pytorch',
      '/zh/posts/pytorch',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/zh/posts/re-soup': RouteRecordInfo<
      '/zh/posts/re-soup',
      '/zh/posts/re-soup',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/zh/posts/rewrite-blazeb2': RouteRecordInfo<
      '/zh/posts/rewrite-blazeb2',
      '/zh/posts/rewrite-blazeb2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/zh/posts/sass': RouteRecordInfo<
      '/zh/posts/sass',
      '/zh/posts/sass',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/zh/posts/swiper': RouteRecordInfo<
      '/zh/posts/swiper',
      '/zh/posts/swiper',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/zh/posts/tkinter': RouteRecordInfo<
      '/zh/posts/tkinter',
      '/zh/posts/tkinter',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/zh/posts/tmpl-cli': RouteRecordInfo<
      '/zh/posts/tmpl-cli',
      '/zh/posts/tmpl-cli',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/zh/posts/train': RouteRecordInfo<
      '/zh/posts/train',
      '/zh/posts/train',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/zh/posts/vscode': RouteRecordInfo<
      '/zh/posts/vscode',
      '/zh/posts/vscode',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/zh/posts/yunsuh-uninstall': RouteRecordInfo<
      '/zh/posts/yunsuh-uninstall',
      '/zh/posts/yunsuh-uninstall',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/zh/posts/zsh-windows': RouteRecordInfo<
      '/zh/posts/zsh-windows',
      '/zh/posts/zsh-windows',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/zh/projects/': RouteRecordInfo<
      '/zh/projects/',
      '/zh/projects',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'pages/en/index.md': {
      routes:
        | '/'
      views:
        | never
    }
    'pages/[...404].md': {
      routes:
        | '/[...404]'
      views:
        | never
    }
    'pages/en/demos/index.md': {
      routes:
        | '/demos/'
      views:
        | never
    }
    'pages/en/interview/index.md': {
      routes:
        | '/interview/'
      views:
        | never
    }
    'pages/en/navs/index.md': {
      routes:
        | '/navs/'
      views:
        | never
    }
    'pages/en/navs/libraries.md': {
      routes:
        | '/navs/libraries'
      views:
        | never
    }
    'pages/en/navs/tools.md': {
      routes:
        | '/navs/tools'
      views:
        | never
    }
    'pages/en/posts/index.md': {
      routes:
        | '/posts/'
      views:
        | never
    }
    'pages/en/posts/2021.md': {
      routes:
        | '/posts/2021'
      views:
        | never
    }
    'pages/en/posts/algolia.md': {
      routes:
        | '/posts/algolia'
      views:
        | never
    }
    'pages/en/posts/aug.md': {
      routes:
        | '/posts/aug'
      views:
        | never
    }
    'pages/en/posts/big-screen.md': {
      routes:
        | '/posts/big-screen'
      views:
        | never
    }
    'pages/en/posts/bs2022.md': {
      routes:
        | '/posts/bs2022'
      views:
        | never
    }
    'pages/en/posts/buy-car.md': {
      routes:
        | '/posts/buy-car'
      views:
        | never
    }
    'pages/en/posts/convolution.md': {
      routes:
        | '/posts/convolution'
      views:
        | never
    }
    'pages/en/posts/debug_test.md': {
      routes:
        | '/posts/debug_test'
      views:
        | never
    }
    'pages/en/posts/deepin.md': {
      routes:
        | '/posts/deepin'
      views:
        | never
    }
    'pages/en/posts/docker.md': {
      routes:
        | '/posts/docker'
      views:
        | never
    }
    'pages/en/posts/es6.md': {
      routes:
        | '/posts/es6'
      views:
        | never
    }
    'pages/en/posts/file-download.md': {
      routes:
        | '/posts/file-download'
      views:
        | never
    }
    'pages/en/posts/forwardemail.md': {
      routes:
        | '/posts/forwardemail'
      views:
        | never
    }
    'pages/en/posts/git.md': {
      routes:
        | '/posts/git'
      views:
        | never
    }
    'pages/en/posts/git-commit.md': {
      routes:
        | '/posts/git-commit'
      views:
        | never
    }
    'pages/en/posts/gpt.md': {
      routes:
        | '/posts/gpt'
      views:
        | never
    }
    'pages/en/posts/java.md': {
      routes:
        | '/posts/java'
      views:
        | never
    }
    'pages/en/posts/js-re.md': {
      routes:
        | '/posts/js-re'
      views:
        | never
    }
    'pages/en/posts/make-name.md': {
      routes:
        | '/posts/make-name'
      views:
        | never
    }
    'pages/en/posts/mcp.md': {
      routes:
        | '/posts/mcp'
      views:
        | never
    }
    'pages/en/posts/md-it-diagarm.md': {
      routes:
        | '/posts/md-it-diagarm'
      views:
        | never
    }
    'pages/en/posts/mermaid.md': {
      routes:
        | '/posts/mermaid'
      views:
        | never
    }
    'pages/en/posts/npm-cdn.md': {
      routes:
        | '/posts/npm-cdn'
      views:
        | never
    }
    'pages/en/posts/ollama.md': {
      routes:
        | '/posts/ollama'
      views:
        | never
    }
    'pages/en/posts/own-api.md': {
      routes:
        | '/posts/own-api'
      views:
        | never
    }
    'pages/en/posts/pinia.md': {
      routes:
        | '/posts/pinia'
      views:
        | never
    }
    'pages/en/posts/pnpm-pkg.md': {
      routes:
        | '/posts/pnpm-pkg'
      views:
        | never
    }
    'pages/en/posts/pytorch.md': {
      routes:
        | '/posts/pytorch'
      views:
        | never
    }
    'pages/en/posts/re-soup.md': {
      routes:
        | '/posts/re-soup'
      views:
        | never
    }
    'pages/en/posts/rewrite-blazeb2.md': {
      routes:
        | '/posts/rewrite-blazeb2'
      views:
        | never
    }
    'pages/en/posts/sass.md': {
      routes:
        | '/posts/sass'
      views:
        | never
    }
    'pages/en/posts/swiper.md': {
      routes:
        | '/posts/swiper'
      views:
        | never
    }
    'pages/en/posts/tkinter.md': {
      routes:
        | '/posts/tkinter'
      views:
        | never
    }
    'pages/en/posts/tmpl-cli.md': {
      routes:
        | '/posts/tmpl-cli'
      views:
        | never
    }
    'pages/en/posts/train.md': {
      routes:
        | '/posts/train'
      views:
        | never
    }
    'pages/en/posts/vscode.md': {
      routes:
        | '/posts/vscode'
      views:
        | never
    }
    'pages/en/posts/yunshu-uninstall.md': {
      routes:
        | '/posts/yunshu-uninstall'
      views:
        | never
    }
    'pages/en/posts/zsh-windows.md': {
      routes:
        | '/posts/zsh-windows'
      views:
        | never
    }
    'pages/en/projects/index.md': {
      routes:
        | '/projects/'
      views:
        | never
    }
    'pages/zh/index.md': {
      routes:
        | '/zh/'
      views:
        | never
    }
    'pages/zh/demos/index.md': {
      routes:
        | '/zh/demos/'
      views:
        | never
    }
    'pages/zh/interview/index.md': {
      routes:
        | '/zh/interview/'
      views:
        | never
    }
    'pages/zh/navs/index.md': {
      routes:
        | '/zh/navs/'
      views:
        | never
    }
    'pages/zh/navs/libraries.md': {
      routes:
        | '/zh/navs/libraries'
      views:
        | never
    }
    'pages/zh/navs/tools.md': {
      routes:
        | '/zh/navs/tools'
      views:
        | never
    }
    'pages/zh/posts/index.md': {
      routes:
        | '/zh/posts/'
      views:
        | never
    }
    'pages/zh/posts/2021.md': {
      routes:
        | '/zh/posts/2021'
      views:
        | never
    }
    'pages/zh/posts/algolia.md': {
      routes:
        | '/zh/posts/algolia'
      views:
        | never
    }
    'pages/zh/posts/aug.md': {
      routes:
        | '/zh/posts/aug'
      views:
        | never
    }
    'pages/zh/posts/big-screen.md': {
      routes:
        | '/zh/posts/big-screen'
      views:
        | never
    }
    'pages/zh/posts/bs2022.md': {
      routes:
        | '/zh/posts/bs2022'
      views:
        | never
    }
    'pages/zh/posts/buy-car.md': {
      routes:
        | '/zh/posts/buy-car'
      views:
        | never
    }
    'pages/zh/posts/convolution.md': {
      routes:
        | '/zh/posts/convolution'
      views:
        | never
    }
    'pages/zh/posts/debug_test.md': {
      routes:
        | '/zh/posts/debug_test'
      views:
        | never
    }
    'pages/zh/posts/deepin.md': {
      routes:
        | '/zh/posts/deepin'
      views:
        | never
    }
    'pages/zh/posts/docker.md': {
      routes:
        | '/zh/posts/docker'
      views:
        | never
    }
    'pages/zh/posts/es6.md': {
      routes:
        | '/zh/posts/es6'
      views:
        | never
    }
    'pages/zh/posts/file-download.md': {
      routes:
        | '/zh/posts/file-download'
      views:
        | never
    }
    'pages/zh/posts/forwardemail.md': {
      routes:
        | '/zh/posts/forwardemail'
      views:
        | never
    }
    'pages/zh/posts/git.md': {
      routes:
        | '/zh/posts/git'
      views:
        | never
    }
    'pages/zh/posts/git-commit.md': {
      routes:
        | '/zh/posts/git-commit'
      views:
        | never
    }
    'pages/zh/posts/gpt.md': {
      routes:
        | '/zh/posts/gpt'
      views:
        | never
    }
    'pages/zh/posts/java.md': {
      routes:
        | '/zh/posts/java'
      views:
        | never
    }
    'pages/zh/posts/js-re.md': {
      routes:
        | '/zh/posts/js-re'
      views:
        | never
    }
    'pages/zh/posts/make-name.md': {
      routes:
        | '/zh/posts/make-name'
      views:
        | never
    }
    'pages/zh/posts/mcp.md': {
      routes:
        | '/zh/posts/mcp'
      views:
        | never
    }
    'pages/zh/posts/md-it-diagarm.md': {
      routes:
        | '/zh/posts/md-it-diagarm'
      views:
        | never
    }
    'pages/zh/posts/mermaid.md': {
      routes:
        | '/zh/posts/mermaid'
      views:
        | never
    }
    'pages/zh/posts/npm-cdn.md': {
      routes:
        | '/zh/posts/npm-cdn'
      views:
        | never
    }
    'pages/zh/posts/ollama.md': {
      routes:
        | '/zh/posts/ollama'
      views:
        | never
    }
    'pages/zh/posts/own-api.md': {
      routes:
        | '/zh/posts/own-api'
      views:
        | never
    }
    'pages/zh/posts/pinia.md': {
      routes:
        | '/zh/posts/pinia'
      views:
        | never
    }
    'pages/zh/posts/pnpm-pkg.md': {
      routes:
        | '/zh/posts/pnpm-pkg'
      views:
        | never
    }
    'pages/zh/posts/pytorch.md': {
      routes:
        | '/zh/posts/pytorch'
      views:
        | never
    }
    'pages/zh/posts/re-soup.md': {
      routes:
        | '/zh/posts/re-soup'
      views:
        | never
    }
    'pages/zh/posts/rewrite-blazeb2.md': {
      routes:
        | '/zh/posts/rewrite-blazeb2'
      views:
        | never
    }
    'pages/zh/posts/sass.md': {
      routes:
        | '/zh/posts/sass'
      views:
        | never
    }
    'pages/zh/posts/swiper.md': {
      routes:
        | '/zh/posts/swiper'
      views:
        | never
    }
    'pages/zh/posts/tkinter.md': {
      routes:
        | '/zh/posts/tkinter'
      views:
        | never
    }
    'pages/zh/posts/tmpl-cli.md': {
      routes:
        | '/zh/posts/tmpl-cli'
      views:
        | never
    }
    'pages/zh/posts/train.md': {
      routes:
        | '/zh/posts/train'
      views:
        | never
    }
    'pages/zh/posts/vscode.md': {
      routes:
        | '/zh/posts/vscode'
      views:
        | never
    }
    'pages/zh/posts/yunsuh-uninstall.md': {
      routes:
        | '/zh/posts/yunsuh-uninstall'
      views:
        | never
    }
    'pages/zh/posts/zsh-windows.md': {
      routes:
        | '/zh/posts/zsh-windows'
      views:
        | never
    }
    'pages/zh/projects/index.md': {
      routes:
        | '/zh/projects/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
