/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...404]': RouteRecordInfo<
      '/[...404]',
      '/:404(.*)',
      { 404: ParamValue<true> },
      { 404: ParamValue<false> },
      | never
    >,
    '/demos/': RouteRecordInfo<
      '/demos/',
      '/demos',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/en/': RouteRecordInfo<
      '/en/',
      '/en',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/en/demos/': RouteRecordInfo<
      '/en/demos/',
      '/en/demos',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/en/interview/': RouteRecordInfo<
      '/en/interview/',
      '/en/interview',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/en/navs/': RouteRecordInfo<
      '/en/navs/',
      '/en/navs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/en/navs/libraries': RouteRecordInfo<
      '/en/navs/libraries',
      '/en/navs/libraries',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/en/navs/tools': RouteRecordInfo<
      '/en/navs/tools',
      '/en/navs/tools',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/en/posts/': RouteRecordInfo<
      '/en/posts/',
      '/en/posts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/en/posts/2021': RouteRecordInfo<
      '/en/posts/2021',
      '/en/posts/2021',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/en/posts/ai-dev-thoughts': RouteRecordInfo<
      '/en/posts/ai-dev-thoughts',
      '/en/posts/ai-dev-thoughts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/en/posts/ai-text': RouteRecordInfo<
      '/en/posts/ai-text',
      '/en/posts/ai-text',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/en/posts/algolia': RouteRecordInfo<
      '/en/posts/algolia',
      '/en/posts/algolia',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/en/posts/aug': RouteRecordInfo<
      '/en/posts/aug',
      '/en/posts/aug',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/en/posts/big-screen': RouteRecordInfo<
      '/en/posts/big-screen',
      '/en/posts/big-screen',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/en/posts/bs2022': RouteRecordInfo<
      '/en/posts/bs2022',
      '/en/posts/bs2022',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/en/posts/buy-car': RouteRecordInfo<
      '/en/posts/buy-car',
      '/en/posts/buy-car',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/en/posts/convolution': RouteRecordInfo<
      '/en/posts/convolution',
      '/en/posts/convolution',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/en/posts/debug_test': RouteRecordInfo<
      '/en/posts/debug_test',
      '/en/posts/debug_test',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/en/posts/deepin': RouteRecordInfo<
      '/en/posts/deepin',
      '/en/posts/deepin',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/en/posts/docker': RouteRecordInfo<
      '/en/posts/docker',
      '/en/posts/docker',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/en/posts/embedded': RouteRecordInfo<
      '/en/posts/embedded',
      '/en/posts/embedded',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/en/posts/es6': RouteRecordInfo<
      '/en/posts/es6',
      '/en/posts/es6',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/en/posts/file-download': RouteRecordInfo<
      '/en/posts/file-download',
      '/en/posts/file-download',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/en/posts/forwardemail': RouteRecordInfo<
      '/en/posts/forwardemail',
      '/en/posts/forwardemail',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/en/posts/git': RouteRecordInfo<
      '/en/posts/git',
      '/en/posts/git',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/en/posts/git-commit': RouteRecordInfo<
      '/en/posts/git-commit',
      '/en/posts/git-commit',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/en/posts/gpt': RouteRecordInfo<
      '/en/posts/gpt',
      '/en/posts/gpt',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/en/posts/grill-me-vs-superpowers': RouteRecordInfo<
      '/en/posts/grill-me-vs-superpowers',
      '/en/posts/grill-me-vs-superpowers',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/en/posts/java': RouteRecordInfo<
      '/en/posts/java',
      '/en/posts/java',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/en/posts/js-re': RouteRecordInfo<
      '/en/posts/js-re',
      '/en/posts/js-re',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/en/posts/mcp': RouteRecordInfo<
      '/en/posts/mcp',
      '/en/posts/mcp',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/en/posts/md-it-diagarm': RouteRecordInfo<
      '/en/posts/md-it-diagarm',
      '/en/posts/md-it-diagarm',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/en/posts/mermaid': RouteRecordInfo<
      '/en/posts/mermaid',
      '/en/posts/mermaid',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/en/posts/npm-cdn': RouteRecordInfo<
      '/en/posts/npm-cdn',
      '/en/posts/npm-cdn',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/en/posts/ollama': RouteRecordInfo<
      '/en/posts/ollama',
      '/en/posts/ollama',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/en/posts/own-api': RouteRecordInfo<
      '/en/posts/own-api',
      '/en/posts/own-api',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/en/posts/pinia': RouteRecordInfo<
      '/en/posts/pinia',
      '/en/posts/pinia',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/en/posts/pnpm-pkg': RouteRecordInfo<
      '/en/posts/pnpm-pkg',
      '/en/posts/pnpm-pkg',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/en/posts/pytorch': RouteRecordInfo<
      '/en/posts/pytorch',
      '/en/posts/pytorch',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/en/posts/re-soup': RouteRecordInfo<
      '/en/posts/re-soup',
      '/en/posts/re-soup',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/en/posts/rewrite-blazeb2': RouteRecordInfo<
      '/en/posts/rewrite-blazeb2',
      '/en/posts/rewrite-blazeb2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/en/posts/sass': RouteRecordInfo<
      '/en/posts/sass',
      '/en/posts/sass',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/en/posts/swiper': RouteRecordInfo<
      '/en/posts/swiper',
      '/en/posts/swiper',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/en/posts/tkinter': RouteRecordInfo<
      '/en/posts/tkinter',
      '/en/posts/tkinter',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/en/posts/tmpl-cli': RouteRecordInfo<
      '/en/posts/tmpl-cli',
      '/en/posts/tmpl-cli',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/en/posts/train': RouteRecordInfo<
      '/en/posts/train',
      '/en/posts/train',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/en/posts/vscode': RouteRecordInfo<
      '/en/posts/vscode',
      '/en/posts/vscode',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/en/posts/yunshu-uninstall': RouteRecordInfo<
      '/en/posts/yunshu-uninstall',
      '/en/posts/yunshu-uninstall',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/en/posts/zsh-windows': RouteRecordInfo<
      '/en/posts/zsh-windows',
      '/en/posts/zsh-windows',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/en/projects/': RouteRecordInfo<
      '/en/projects/',
      '/en/projects',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/interview/': RouteRecordInfo<
      '/interview/',
      '/interview',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/navs/': RouteRecordInfo<
      '/navs/',
      '/navs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/navs/libraries': RouteRecordInfo<
      '/navs/libraries',
      '/navs/libraries',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/navs/tools': RouteRecordInfo<
      '/navs/tools',
      '/navs/tools',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/': RouteRecordInfo<
      '/posts/',
      '/posts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/2021': RouteRecordInfo<
      '/posts/2021',
      '/posts/2021',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/5132': RouteRecordInfo<
      '/posts/5132',
      '/posts/5132',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/ai-dev-thoughts': RouteRecordInfo<
      '/posts/ai-dev-thoughts',
      '/posts/ai-dev-thoughts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/ai-text': RouteRecordInfo<
      '/posts/ai-text',
      '/posts/ai-text',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/algolia': RouteRecordInfo<
      '/posts/algolia',
      '/posts/algolia',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/aug': RouteRecordInfo<
      '/posts/aug',
      '/posts/aug',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/big-screen': RouteRecordInfo<
      '/posts/big-screen',
      '/posts/big-screen',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/bitwise': RouteRecordInfo<
      '/posts/bitwise',
      '/posts/bitwise',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/bs2022': RouteRecordInfo<
      '/posts/bs2022',
      '/posts/bs2022',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/buy-car': RouteRecordInfo<
      '/posts/buy-car',
      '/posts/buy-car',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/c': RouteRecordInfo<
      '/posts/c',
      '/posts/c',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/convolution': RouteRecordInfo<
      '/posts/convolution',
      '/posts/convolution',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cplusplus': RouteRecordInfo<
      '/posts/cplusplus',
      '/posts/cplusplus',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/data_struct': RouteRecordInfo<
      '/posts/data_struct',
      '/posts/data_struct',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/database': RouteRecordInfo<
      '/posts/database',
      '/posts/database',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/debug_test': RouteRecordInfo<
      '/posts/debug_test',
      '/posts/debug_test',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/deepin': RouteRecordInfo<
      '/posts/deepin',
      '/posts/deepin',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/docker': RouteRecordInfo<
      '/posts/docker',
      '/posts/docker',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/embd_used_soft': RouteRecordInfo<
      '/posts/embd_used_soft',
      '/posts/embd_used_soft',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/embedded': RouteRecordInfo<
      '/posts/embedded',
      '/posts/embedded',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/es6': RouteRecordInfo<
      '/posts/es6',
      '/posts/es6',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/file-download': RouteRecordInfo<
      '/posts/file-download',
      '/posts/file-download',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/fileio': RouteRecordInfo<
      '/posts/fileio',
      '/posts/fileio',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/forwardemail': RouteRecordInfo<
      '/posts/forwardemail',
      '/posts/forwardemail',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/git': RouteRecordInfo<
      '/posts/git',
      '/posts/git',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/git-commit': RouteRecordInfo<
      '/posts/git-commit',
      '/posts/git-commit',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/gpt': RouteRecordInfo<
      '/posts/gpt',
      '/posts/gpt',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/grill-me-vs-superpowers': RouteRecordInfo<
      '/posts/grill-me-vs-superpowers',
      '/posts/grill-me-vs-superpowers',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/ipc': RouteRecordInfo<
      '/posts/ipc',
      '/posts/ipc',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/java': RouteRecordInfo<
      '/posts/java',
      '/posts/java',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/js-re': RouteRecordInfo<
      '/posts/js-re',
      '/posts/js-re',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/linux': RouteRecordInfo<
      '/posts/linux',
      '/posts/linux',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/mac_emd': RouteRecordInfo<
      '/posts/mac_emd',
      '/posts/mac_emd',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/makefile': RouteRecordInfo<
      '/posts/makefile',
      '/posts/makefile',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/mcp': RouteRecordInfo<
      '/posts/mcp',
      '/posts/mcp',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/md-it-diagarm': RouteRecordInfo<
      '/posts/md-it-diagarm',
      '/posts/md-it-diagarm',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/mermaid': RouteRecordInfo<
      '/posts/mermaid',
      '/posts/mermaid',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/npm-cdn': RouteRecordInfo<
      '/posts/npm-cdn',
      '/posts/npm-cdn',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/ollama': RouteRecordInfo<
      '/posts/ollama',
      '/posts/ollama',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/own-api': RouteRecordInfo<
      '/posts/own-api',
      '/posts/own-api',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/pinia': RouteRecordInfo<
      '/posts/pinia',
      '/posts/pinia',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/pnpm-pkg': RouteRecordInfo<
      '/posts/pnpm-pkg',
      '/posts/pnpm-pkg',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/pointer': RouteRecordInfo<
      '/posts/pointer',
      '/posts/pointer',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/pthread': RouteRecordInfo<
      '/posts/pthread',
      '/posts/pthread',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/pytorch': RouteRecordInfo<
      '/posts/pytorch',
      '/posts/pytorch',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/re-soup': RouteRecordInfo<
      '/posts/re-soup',
      '/posts/re-soup',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/rewrite-blazeb2': RouteRecordInfo<
      '/posts/rewrite-blazeb2',
      '/posts/rewrite-blazeb2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/sass': RouteRecordInfo<
      '/posts/sass',
      '/posts/sass',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/swiper': RouteRecordInfo<
      '/posts/swiper',
      '/posts/swiper',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/tkinter': RouteRecordInfo<
      '/posts/tkinter',
      '/posts/tkinter',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/tmpl-cli': RouteRecordInfo<
      '/posts/tmpl-cli',
      '/posts/tmpl-cli',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/train': RouteRecordInfo<
      '/posts/train',
      '/posts/train',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/vscode': RouteRecordInfo<
      '/posts/vscode',
      '/posts/vscode',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/yunsuh-uninstall': RouteRecordInfo<
      '/posts/yunsuh-uninstall',
      '/posts/yunsuh-uninstall',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/zsh-windows': RouteRecordInfo<
      '/posts/zsh-windows',
      '/posts/zsh-windows',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/projects/': RouteRecordInfo<
      '/projects/',
      '/projects',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'pages/zh/index.md': {
      routes:
        | '/'
      views:
        | never
    }
    'pages/[...404].md': {
      routes:
        | '/[...404]'
      views:
        | never
    }
    'pages/zh/demos/index.md': {
      routes:
        | '/demos/'
      views:
        | never
    }
    'pages/en/index.md': {
      routes:
        | '/en/'
      views:
        | never
    }
    'pages/en/demos/index.md': {
      routes:
        | '/en/demos/'
      views:
        | never
    }
    'pages/en/interview/index.md': {
      routes:
        | '/en/interview/'
      views:
        | never
    }
    'pages/en/navs/index.md': {
      routes:
        | '/en/navs/'
      views:
        | never
    }
    'pages/en/navs/libraries.md': {
      routes:
        | '/en/navs/libraries'
      views:
        | never
    }
    'pages/en/navs/tools.md': {
      routes:
        | '/en/navs/tools'
      views:
        | never
    }
    'pages/en/posts/index.md': {
      routes:
        | '/en/posts/'
      views:
        | never
    }
    'pages/en/posts/2021.md': {
      routes:
        | '/en/posts/2021'
      views:
        | never
    }
    'pages/en/posts/ai-dev-thoughts.md': {
      routes:
        | '/en/posts/ai-dev-thoughts'
      views:
        | never
    }
    'pages/en/posts/ai-text.md': {
      routes:
        | '/en/posts/ai-text'
      views:
        | never
    }
    'pages/en/posts/algolia.md': {
      routes:
        | '/en/posts/algolia'
      views:
        | never
    }
    'pages/en/posts/aug.md': {
      routes:
        | '/en/posts/aug'
      views:
        | never
    }
    'pages/en/posts/big-screen.md': {
      routes:
        | '/en/posts/big-screen'
      views:
        | never
    }
    'pages/en/posts/bs2022.md': {
      routes:
        | '/en/posts/bs2022'
      views:
        | never
    }
    'pages/en/posts/buy-car.md': {
      routes:
        | '/en/posts/buy-car'
      views:
        | never
    }
    'pages/en/posts/convolution.md': {
      routes:
        | '/en/posts/convolution'
      views:
        | never
    }
    'pages/en/posts/debug_test.md': {
      routes:
        | '/en/posts/debug_test'
      views:
        | never
    }
    'pages/en/posts/deepin.md': {
      routes:
        | '/en/posts/deepin'
      views:
        | never
    }
    'pages/en/posts/docker.md': {
      routes:
        | '/en/posts/docker'
      views:
        | never
    }
    'pages/en/posts/embedded.md': {
      routes:
        | '/en/posts/embedded'
      views:
        | never
    }
    'pages/en/posts/es6.md': {
      routes:
        | '/en/posts/es6'
      views:
        | never
    }
    'pages/en/posts/file-download.md': {
      routes:
        | '/en/posts/file-download'
      views:
        | never
    }
    'pages/en/posts/forwardemail.md': {
      routes:
        | '/en/posts/forwardemail'
      views:
        | never
    }
    'pages/en/posts/git.md': {
      routes:
        | '/en/posts/git'
      views:
        | never
    }
    'pages/en/posts/git-commit.md': {
      routes:
        | '/en/posts/git-commit'
      views:
        | never
    }
    'pages/en/posts/gpt.md': {
      routes:
        | '/en/posts/gpt'
      views:
        | never
    }
    'pages/en/posts/grill-me-vs-superpowers.md': {
      routes:
        | '/en/posts/grill-me-vs-superpowers'
      views:
        | never
    }
    'pages/en/posts/java.md': {
      routes:
        | '/en/posts/java'
      views:
        | never
    }
    'pages/en/posts/js-re.md': {
      routes:
        | '/en/posts/js-re'
      views:
        | never
    }
    'pages/en/posts/mcp.md': {
      routes:
        | '/en/posts/mcp'
      views:
        | never
    }
    'pages/en/posts/md-it-diagarm.md': {
      routes:
        | '/en/posts/md-it-diagarm'
      views:
        | never
    }
    'pages/en/posts/mermaid.md': {
      routes:
        | '/en/posts/mermaid'
      views:
        | never
    }
    'pages/en/posts/npm-cdn.md': {
      routes:
        | '/en/posts/npm-cdn'
      views:
        | never
    }
    'pages/en/posts/ollama.md': {
      routes:
        | '/en/posts/ollama'
      views:
        | never
    }
    'pages/en/posts/own-api.md': {
      routes:
        | '/en/posts/own-api'
      views:
        | never
    }
    'pages/en/posts/pinia.md': {
      routes:
        | '/en/posts/pinia'
      views:
        | never
    }
    'pages/en/posts/pnpm-pkg.md': {
      routes:
        | '/en/posts/pnpm-pkg'
      views:
        | never
    }
    'pages/en/posts/pytorch.md': {
      routes:
        | '/en/posts/pytorch'
      views:
        | never
    }
    'pages/en/posts/re-soup.md': {
      routes:
        | '/en/posts/re-soup'
      views:
        | never
    }
    'pages/en/posts/rewrite-blazeb2.md': {
      routes:
        | '/en/posts/rewrite-blazeb2'
      views:
        | never
    }
    'pages/en/posts/sass.md': {
      routes:
        | '/en/posts/sass'
      views:
        | never
    }
    'pages/en/posts/swiper.md': {
      routes:
        | '/en/posts/swiper'
      views:
        | never
    }
    'pages/en/posts/tkinter.md': {
      routes:
        | '/en/posts/tkinter'
      views:
        | never
    }
    'pages/en/posts/tmpl-cli.md': {
      routes:
        | '/en/posts/tmpl-cli'
      views:
        | never
    }
    'pages/en/posts/train.md': {
      routes:
        | '/en/posts/train'
      views:
        | never
    }
    'pages/en/posts/vscode.md': {
      routes:
        | '/en/posts/vscode'
      views:
        | never
    }
    'pages/en/posts/yunshu-uninstall.md': {
      routes:
        | '/en/posts/yunshu-uninstall'
      views:
        | never
    }
    'pages/en/posts/zsh-windows.md': {
      routes:
        | '/en/posts/zsh-windows'
      views:
        | never
    }
    'pages/en/projects/index.md': {
      routes:
        | '/en/projects/'
      views:
        | never
    }
    'pages/zh/interview/index.md': {
      routes:
        | '/interview/'
      views:
        | never
    }
    'pages/zh/navs/index.md': {
      routes:
        | '/navs/'
      views:
        | never
    }
    'pages/zh/navs/libraries.md': {
      routes:
        | '/navs/libraries'
      views:
        | never
    }
    'pages/zh/navs/tools.md': {
      routes:
        | '/navs/tools'
      views:
        | never
    }
    'pages/zh/posts/index.md': {
      routes:
        | '/posts/'
      views:
        | never
    }
    'pages/zh/posts/2021.md': {
      routes:
        | '/posts/2021'
      views:
        | never
    }
    'pages/zh/posts/5132.md': {
      routes:
        | '/posts/5132'
      views:
        | never
    }
    'pages/zh/posts/ai-dev-thoughts.md': {
      routes:
        | '/posts/ai-dev-thoughts'
      views:
        | never
    }
    'pages/zh/posts/ai-text.md': {
      routes:
        | '/posts/ai-text'
      views:
        | never
    }
    'pages/zh/posts/algolia.md': {
      routes:
        | '/posts/algolia'
      views:
        | never
    }
    'pages/zh/posts/aug.md': {
      routes:
        | '/posts/aug'
      views:
        | never
    }
    'pages/zh/posts/big-screen.md': {
      routes:
        | '/posts/big-screen'
      views:
        | never
    }
    'pages/zh/posts/bitwise.md': {
      routes:
        | '/posts/bitwise'
      views:
        | never
    }
    'pages/zh/posts/bs2022.md': {
      routes:
        | '/posts/bs2022'
      views:
        | never
    }
    'pages/zh/posts/buy-car.md': {
      routes:
        | '/posts/buy-car'
      views:
        | never
    }
    'pages/zh/posts/c.md': {
      routes:
        | '/posts/c'
      views:
        | never
    }
    'pages/zh/posts/convolution.md': {
      routes:
        | '/posts/convolution'
      views:
        | never
    }
    'pages/zh/posts/cplusplus.md': {
      routes:
        | '/posts/cplusplus'
      views:
        | never
    }
    'pages/zh/posts/data_struct.md': {
      routes:
        | '/posts/data_struct'
      views:
        | never
    }
    'pages/zh/posts/database.md': {
      routes:
        | '/posts/database'
      views:
        | never
    }
    'pages/zh/posts/debug_test.md': {
      routes:
        | '/posts/debug_test'
      views:
        | never
    }
    'pages/zh/posts/deepin.md': {
      routes:
        | '/posts/deepin'
      views:
        | never
    }
    'pages/zh/posts/docker.md': {
      routes:
        | '/posts/docker'
      views:
        | never
    }
    'pages/zh/posts/embd_used_soft.md': {
      routes:
        | '/posts/embd_used_soft'
      views:
        | never
    }
    'pages/zh/posts/embedded.md': {
      routes:
        | '/posts/embedded'
      views:
        | never
    }
    'pages/zh/posts/es6.md': {
      routes:
        | '/posts/es6'
      views:
        | never
    }
    'pages/zh/posts/file-download.md': {
      routes:
        | '/posts/file-download'
      views:
        | never
    }
    'pages/zh/posts/fileio.md': {
      routes:
        | '/posts/fileio'
      views:
        | never
    }
    'pages/zh/posts/forwardemail.md': {
      routes:
        | '/posts/forwardemail'
      views:
        | never
    }
    'pages/zh/posts/git.md': {
      routes:
        | '/posts/git'
      views:
        | never
    }
    'pages/zh/posts/git-commit.md': {
      routes:
        | '/posts/git-commit'
      views:
        | never
    }
    'pages/zh/posts/gpt.md': {
      routes:
        | '/posts/gpt'
      views:
        | never
    }
    'pages/zh/posts/grill-me-vs-superpowers.md': {
      routes:
        | '/posts/grill-me-vs-superpowers'
      views:
        | never
    }
    'pages/zh/posts/ipc.md': {
      routes:
        | '/posts/ipc'
      views:
        | never
    }
    'pages/zh/posts/java.md': {
      routes:
        | '/posts/java'
      views:
        | never
    }
    'pages/zh/posts/js-re.md': {
      routes:
        | '/posts/js-re'
      views:
        | never
    }
    'pages/zh/posts/linux.md': {
      routes:
        | '/posts/linux'
      views:
        | never
    }
    'pages/zh/posts/mac_emd.md': {
      routes:
        | '/posts/mac_emd'
      views:
        | never
    }
    'pages/zh/posts/makefile.md': {
      routes:
        | '/posts/makefile'
      views:
        | never
    }
    'pages/zh/posts/mcp.md': {
      routes:
        | '/posts/mcp'
      views:
        | never
    }
    'pages/zh/posts/md-it-diagarm.md': {
      routes:
        | '/posts/md-it-diagarm'
      views:
        | never
    }
    'pages/zh/posts/mermaid.md': {
      routes:
        | '/posts/mermaid'
      views:
        | never
    }
    'pages/zh/posts/npm-cdn.md': {
      routes:
        | '/posts/npm-cdn'
      views:
        | never
    }
    'pages/zh/posts/ollama.md': {
      routes:
        | '/posts/ollama'
      views:
        | never
    }
    'pages/zh/posts/own-api.md': {
      routes:
        | '/posts/own-api'
      views:
        | never
    }
    'pages/zh/posts/pinia.md': {
      routes:
        | '/posts/pinia'
      views:
        | never
    }
    'pages/zh/posts/pnpm-pkg.md': {
      routes:
        | '/posts/pnpm-pkg'
      views:
        | never
    }
    'pages/zh/posts/pointer.md': {
      routes:
        | '/posts/pointer'
      views:
        | never
    }
    'pages/zh/posts/pthread.md': {
      routes:
        | '/posts/pthread'
      views:
        | never
    }
    'pages/zh/posts/pytorch.md': {
      routes:
        | '/posts/pytorch'
      views:
        | never
    }
    'pages/zh/posts/re-soup.md': {
      routes:
        | '/posts/re-soup'
      views:
        | never
    }
    'pages/zh/posts/rewrite-blazeb2.md': {
      routes:
        | '/posts/rewrite-blazeb2'
      views:
        | never
    }
    'pages/zh/posts/sass.md': {
      routes:
        | '/posts/sass'
      views:
        | never
    }
    'pages/zh/posts/swiper.md': {
      routes:
        | '/posts/swiper'
      views:
        | never
    }
    'pages/zh/posts/tkinter.md': {
      routes:
        | '/posts/tkinter'
      views:
        | never
    }
    'pages/zh/posts/tmpl-cli.md': {
      routes:
        | '/posts/tmpl-cli'
      views:
        | never
    }
    'pages/zh/posts/train.md': {
      routes:
        | '/posts/train'
      views:
        | never
    }
    'pages/zh/posts/vscode.md': {
      routes:
        | '/posts/vscode'
      views:
        | never
    }
    'pages/zh/posts/yunsuh-uninstall.md': {
      routes:
        | '/posts/yunsuh-uninstall'
      views:
        | never
    }
    'pages/zh/posts/zsh-windows.md': {
      routes:
        | '/posts/zsh-windows'
      views:
        | never
    }
    'pages/zh/projects/index.md': {
      routes:
        | '/projects/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
