name: Run Docker Container

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml

      - name: fetch config links
        run: |
          python scripts/read_sitemap.py

      - name: Set up Environment Variables
        env:
          APP_ID: ${{ secrets.APP_ID }}
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          echo "APPLICATION_ID=$APP_ID" > .env
          echo "API_KEY=$API_KEY" >> .env

      - name: Run Docker container
        run: |
          docker run --env-file=.env -e "CONFIG=$(cat config.json | jq -r tostring)" algolia/docsearch-scraper